"""Drop country/language from user_progress and add FK

Revision ID: 176e1d11c3fc
Revises: 7fe18fe78047
Create Date: 2025-05-25 17:48:56.516322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176e1d11c3fc'
down_revision: Union[str, None] = '7fe18fe78047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_progress", "country")
    op.drop_column("user_progress", "language")
    op.create_foreign_key(None, 'user_progress', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    # ### end Alembic commands ###
