"""Drop country/language from user_progress, add FK to questions

Revision ID: 7fe18fe78047
Revises: 8492ab242a16
Create Date: 2025-05-25 16:51:58.774284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe18fe78047'
down_revision: Union[str, None] = '8492ab242a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_progress_question_id_fkey'), 'user_progress', type_='foreignkey')
    op.drop_column('user_progress', 'country')
    op.drop_column('user_progress', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('language', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_progress', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('user_progress_question_id_fkey'), 'user_progress', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
