"""Use timestamptz for user_progress timestamps

Revision ID: effcb7a5c416
Revises: 1d96e10d1099
Create Date: 2025-05-25 11:25:44.738261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effcb7a5c416'
down_revision: Union[str, None] = '1d96e10d1099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_progress', 'repetition_count',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=False)
    op.drop_constraint(op.f('user_progress_question_id_fkey'), 'user_progress', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('user_progress_question_id_fkey'), 'user_progress', 'questions', ['question_id'], ['id'])
    op.alter_column('user_progress', 'repetition_count',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
